[package]
name = "clickhouse-test"
version = "0.1.0"
authors = ["Kevin Zumueller <kevin@zumueller.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "^20"